added code for create designation
sunbird-cb/karmaquest-servcie pull request #92
Opened 2024-07-12 12:08 UTC by anilkumarkammalapalli

2024-07-17 05:09 UTC, karthik-tarento requested changes

2024-07-17 05:09 UTC, karthik-tarento commented on src/main/java/com/igot/cb/designation/service/impl/DesignationServiceImpl.java
> +      strUrl.append(cbProperties.getOdcsTermCrete()).append("/").append(Id).append("?framework=")
why are we using cbProperties.getOdcsTermCreate() method here ??
it suppose to read right ?

2024-07-17 05:09 UTC, karthik-tarento commented on src/main/java/com/igot/cb/designation/service/impl/DesignationServiceImpl.java
> +                  cbProperties.getOdcsFrameworkName() + "_" + cbProperties.getOdcsCategoryName());
both of this property looks like common one... instead these should be named with odcsDesignationFramework and odcsDesignationCategory

2024-07-17 05:09 UTC, karthik-tarento commented on src/main/java/com/igot/cb/designation/service/impl/DesignationServiceImpl.java
> +    } else
Code is not formatted properly

2024-07-17 05:09 UTC, karthik-tarento commented on src/main/java/com/igot/cb/designation/service/impl/DesignationServiceImpl.java
> +    payloadValidation.validatePayload(Constants.DESIGNATION_CREATE_PAYLOAD_VALIDATION,request);
what happens when validation fails ?

2024-07-17 05:09 UTC, karthik-tarento commented on src/main/java/com/igot/cb/pores/util/CbProperties.java
> +public class CbProperties {
Don't we have properties class already ??
why we need new class ?

2024-07-17 05:09 UTC, karthik-tarento commented on src/main/resources/application.properties
> +odcs.category.name=
are these used only for designation ?? is it designation master / adding designation to org ?

2024-07-18 07:08 UTC, sureshece16 approved these changes

2024-07-18 07:09 UTC, merged